### ISSUE TITLE
image rotation CAPTYCHA returned message

### ISSUE THREAD

**Issue by dstanko001** [pwc-technology-be/eu-captcha#107]
The English version of the returned message on unsuccessful CAPTCHA validation is the same as the alphanumeric CAPTCHA - "The text you have enterd does not match. Please try again." It should be customized for image rotation captcha. There is a typo too - enterd should be entered

**Comment by YvesMeersmans** [comment]
Returned messages are now multilingual but typo is not fixed yet.

**Comment by YvesMeersmans** [comment]
In dutch, there is a space floating at the end of the first sentence. 
"De afbeelding stond niet rechtop ." => "De afbeelding stond niet rechtop."

**Comment by Eddy-Hoevenaers** [comment]
Fixed in the next pull request.
