### ISSUE TITLE
Image rotation CAPTCHA - image not always rotated

### ISSUE THREAD

**Issue by dstanko001** [pwc-technology-be/EU-CAPTCHA#108]
In some instances the image is loading not rotated and you can just validate it. It should be rotated to some degree by default. This will make it so that at least ‘some’ user action needs to be taken to have the image rotated correctly before being validated positively.

**Comment by Eddy-Hoevenaers** [comment]
Fix is in next pull request

**Comment by YvesMeersmans** [comment]
Not fixed yet @Eddy-Hoevenaers . I still get images that are upright immediately. This is however not critical for v1.2 release.

**Comment by YvesMeersmans** [comment]
fixed
