### ISSUE TITLE
Some captcha almost impossible to be read by a human

### ISSUE THREAD

**Issue by jsatec-pm** [pwc-technology-be/EU-CAPTCHA#135]
Hi, 
I noted at least two cases when the characters are so close or even overlapping that it makes it almost impossible for a human to read it (see attached), may be put a bit more space between characters
![Impossible captcha to read -v1](https://user-images.githubusercontent.com/69461637/135463351-0bf92146-9fff-4647-8509-2a0c6e014431.JPG)
![Impossible captcha to read -v2](https://user-images.githubusercontent.com/69461637/135463419-d7d5fd90-fa5e-453f-b2b9-01e04be77f5f.JPG)

**Comment by YvesMeersmans** [comment]
We will increase the space between the characters.

**Comment by Eddy-Hoevenaers** [comment]
I added some more space in the latest version, deployed on DEV and QA

**Comment by jsatec-pm** [comment]
Hi Eddy, thanks, looks good now on all captcha we looked
