### ISSUE TITLE
Audio captcha does not contain 4 characters

### ISSUE THREAD

**Issue by jsatec-pm** [pwc-technology-be/EU-CAPTCHA#136]
I noticed that some audio captcha does not contain the number of characters displayed on the captcha (hear the two recording for EN where you can only hear 3 characters whereas it is supposed to have 4 characters
[recordings.zip](https://github.com/pwc-technology-be/EU-CAPTCHA/files/7260427/recordings.zip)
)

**Comment by YvesMeersmans** [comment]
This is something we cannot recreate. We will align with you on this in a bilateral call.

**Comment by Eddy-Hoevenaers** [comment]
Added 1 second of silence in the latest version, deployed to the DEV and QA  environment
