### ISSUE TITLE
Impossible to distinguish a b from a p in the french audio

### ISSUE THREAD

**Issue by jsatec-pm** [pwc-technology-be/EU-CAPTCHA#137]
See the picture and hear the audio.
As french speaker, I would have put a b  but in fact it is a p
I did not check all the languages but sure there would be similar cases
![PB](https://user-images.githubusercontent.com/69461637/135480371-db7ddc34-1eb6-4e0e-bd82-55c9d1fbfb8d.JPG)
[New Recording 63.zip](https://github.com/pwc-technology-be/EU-CAPTCHA/files/7260468/New.Recording.63.zip)
.

**Comment by YvesMeersmans** [comment]
done
