### ISSUE TITLE
Do not manage to make any successful validation using audio captcha

### ISSUE THREAD

**Issue by jsatec-pm** [pwc-technology-be/EU-CAPTCHA#138]
Hi, see attachment
[audio captcha failures.pdf](https://github.com/pwc-technology-be/EU-CAPTCHA/files/7261547/audio.captcha.failures.pdf)

**Comment by jsatec-pm** [comment]
Hi, additional information after we set the parameter audio captcha to true.
We managed to solve some captcha but still a lot are failings
[Additional input for Audio captcha.pdf](https://github.com/pwc-technology-be/EU-CAPTCHA/files/7269936/Additional.input.for.Audio.captcha.pdf)

**Comment by YvesMeersmans** [comment]
We are looking into this.

**Comment by Eddy-Hoevenaers** [comment]
The problem was that we had 2 instances running and an validation request was forwarded to a different instance than the original get request was made. 
We solved this with adding CORS cookies to the calls so every subsequent call is routed to the same instance on AWS

**Comment by YvesMeersmans** [comment]
@jsatec-pm  Please let us know whether the latest version and the newest client files (v2.2.2) fixes your issue.
