### ISSUE TITLE
Could you provide a new version of the Angular client

### ISSUE THREAD

**Issue by jsatec-pm** [pwc-technology-be/EU-CAPTCHA#141]
Hello,

We noted that the last update on the version of the Angular client is still from 5 month ago.
The calls to the Captcha APIs has changed since then and would be quite helpful to have current example of how to get the different captchas, how to reload and to validate them and all the settings that you use.

Thank you,

Kr,

Jérôme

**Comment by YvesMeersmans** [comment]
A new version of the Angular client will be foreseen.

**Comment by Eddy-Hoevenaers** [comment]
Updated functionality in the Angular client files
