### ISSUE TITLE
Remove K, k, S, s,  Z, z and X, x

### ISSUE THREAD

**Issue by jsatec-pm** [pwc-technology-be/EU-CAPTCHA#143]
Hello,

With the idea that a captcha should not be a quizz but though difficult for robot should avoid as much as possible any confusion made by human,  I would propose to remove the following letters for which upper and lower characters are very similar so that there is less possibility for a human to make a mistake (the same way as you remove the o O 0 and o)

K k

S s

Z z

x X

**Comment by YvesMeersmans** [comment]
done
