### ISSUE TITLE
Test captcha service does not return a captcha for the following languages: cs, de, el, lv, lt, mt, pl, sk, fi, sv, bg, hr

### ISSUE THREAD

**Issue by jsatec-pm** [pwc-technology-be/EU-CAPTCHA#155]
We noticed that for some languages the test service captcha does not return a captcha:
This is for the following languages: cs, de, el, lv, lt, mt, pl, sk, fi, sv, bg, hr

How to reproduce this bug:
Go to our test application page: https://webgate.acceptance.ec.europa.eu/ECI-OCS-6/public 
choose a language that is not one of the above language, (e.g. French), select the nationality French, the captcha will display
Close your browser and go to the same application, select one of the above language, select the nationality French, the captcha will not display this time

**Comment by jsatec-pm** [comment]
Hi @Eddy-Hoevenaers , @YvesMeersmans ,
Additional input from today 10th Nov.
Following languages that are not working are :  lv, lt, hu, ro, fi and de is giving problems randomly
You can easily reproduce the problem by going to your own test implementation at https://testapi.eucaptcha.eu/ just select lv ( https://testapi.eucaptcha.eu/?lang=lv-LV ) and you will see that the captcha image is not displayed
![image](https://user-images.githubusercontent.com/69461637/141094233-782e47f9-3856-403d-b424-d44dcea9cf27.png)

**Comment by Eddy-Hoevenaers** [comment]
I just deployed a new version on the QA environment (https://testapi.eucaptcha.eu) and didn't had the issue anymore. I alsotested a few times using the webgate link and didn't had the issue neither.

Can you please checkand confirm?

**Comment by Eddy-Hoevenaers** [comment]
Fix confirmed on Friday 19/11/2021 by Jérôme so issue can be closed

**Comment by jsatec-pm** [comment]
Hi Eddy, Thanks for that, working fine indeed
