### ISSUE TITLE
removing v V characters

### ISSUE THREAD

**Issue by jsatec-pm** [pwc-technology-be/EU-CAPTCHA#156]
Hello,

the V and v characters are also quite similar and prone to errors for a human so would propose to remove them as well from the offered alphanumeric characters.

Kr,

Jérôme

**Comment by Eddy-Hoevenaers** [comment]
I removed the v and V in the latest version, deployed on DEV and QA

**Comment by jsatec-pm** [comment]
Thanks Eddy, indeed, I did not see it anymore after my tests
