### ISSUE TITLE
spring-boot-starter-tomcat dependency cannot be provided 

### ISSUE THREAD

**Issue by kvandermast** [pwc-technology-be/eu-captcha#28]
You're providing a Spring Boot runnable application
```
	public static void main(String[] args) {
		SpringApplication.run(EuCaptchaApplication.class, args);
	}
```
 so the dependency cannot be "provided":

https://github.com/pwc-technology-be/eu-captcha/blob/a9afdc95b4483782034d7dc4c9b39efbbc9e8bf0/pom.xml#L40-L44

**Comment by Eddy-Hoevenaers** [comment]
From the SpringBoot documentation: https://docs.spring.io/spring-boot/docs/current/reference/html/howto.html#howto-traditional-deployment

If you use the Spring Boot build tools, marking the embedded servlet container dependency as provided produces an executable war file with the provided dependencies packaged in a lib-provided directory. This means that, in addition to being deployable to a servlet container, you can also run your application by using java -jar on the command line.

We meet all the conditions mentioned in this documentation and i tested it  on the command line by using 'java -jar EuCaptcha.war'. The application started without any problem.

**Comment by YvesMeersmans** [comment]
@kvandermast Eddy provided an explanation. Do you understand/agree?
