### ISSUE TITLE
Remove unused resource mapping: webjars

### ISSUE THREAD

**Issue by kvandermast** [pwc-technology-be/eu-captcha#30]
WebJars are not used.

https://github.com/pwc-technology-be/eu-captcha/blob/a9afdc95b4483782034d7dc4c9b39efbbc9e8bf0/src/main/java/com/sii/eucaptcha/configuration/WebConfig.java#L116-L118

**Comment by Eddy-Hoevenaers** [comment]
Removed unused mapping
