### ISSUE TITLE
Code maturity: simplify if-statement

### ISSUE THREAD

**Issue by kvandermast** [pwc-technology-be/eu-captcha#32]
Result of the equals is your result... 

https://github.com/pwc-technology-be/eu-captcha/blob/a9afdc95b4483782034d7dc4c9b39efbbc9e8bf0/src/main/java/com/sii/eucaptcha/security/JwtToken.java#L40-L44

**Comment by Eddy-Hoevenaers** [comment]
Simplified if-statement
