### ISSUE TITLE
Code maturity: JwtToken implementation does not add much 'security'

### ISSUE THREAD

**Issue by kvandermast** [pwc-technology-be/eu-captcha#33]
In the first iteration, the value was just a plain string that was compared, now the string comes from a resource bundle that is shipped with the application.

Apply the no-knowledge principle, or the Proof-of-possession idiom.

https://github.com/pwc-technology-be/eu-captcha/blob/a9afdc95b4483782034d7dc4c9b39efbbc9e8bf0/src/main/java/com/sii/eucaptcha/security/JwtToken.java#L16-L21

**Comment by Eddy-Hoevenaers** [comment]
Implemented the token validation with a key generator and an ID to validate
