### ISSUE TITLE
Improvement: move to configuration files

### ISSUE THREAD

**Issue by kvandermast** [pwc-technology-be/eu-captcha#34]
Maximize configuration. Don't hard-code values.

https://github.com/pwc-technology-be/eu-captcha/blob/a9afdc95b4483782034d7dc4c9b39efbbc9e8bf0/src/main/java/com/sii/eucaptcha/captcha/audio/noise/impl/EuCaptchaNoiseProducer.java#L22-L23

**Comment by Eddy-Hoevenaers** [comment]
Zombie.wav is used now

**Comment by YvesMeersmans** [comment]
@Eddy-Hoevenaers Can you please specify how this fixes the issue?

**Comment by Eddy-Hoevenaers** [comment]
@YvesMeersmans this comment was wrong, it was for issue #29

**Comment by Eddy-Hoevenaers** [comment]
Moved the noise wav files to the properties file
