### ISSUE TITLE
Code maturity: JavaDoc + method signature

### ISSUE THREAD

**Issue by kvandermast** [pwc-technology-be/eu-captcha#35]
- Method signature should match interface defintion. 'target' as parameter name has no added value;
- Missing JavaDoc

https://github.com/pwc-technology-be/eu-captcha/blob/a9afdc95b4483782034d7dc4c9b39efbbc9e8bf0/src/main/java/com/sii/eucaptcha/captcha/audio/noise/NoiseProducer.java#L9

**Comment by Eddy-Hoevenaers** [comment]
Fixed method signature to produceNoise and added JavaDoc
