### ISSUE TITLE
Code maturity: move to resource bundle

### ISSUE THREAD

**Issue by kvandermast** [pwc-technology-be/eu-captcha#36]
Move the VoiceMap class to a resource bundles:
- bundle with the available locales
- bundle with the available/allowed/configurable alphabets per locale
- mapping the locales and alphabets to the files

https://github.com/pwc-technology-be/eu-captcha/blob/a9afdc95b4483782034d7dc4c9b39efbbc9e8bf0/src/main/java/com/sii/eucaptcha/captcha/audio/voice/impl/VoiceMap.java#L13

The same applies for

https://github.com/pwc-technology-be/eu-captcha/blob/a9afdc95b4483782034d7dc4c9b39efbbc9e8bf0/src/main/java/com/sii/eucaptcha/captcha/text/textProducer/impl/LanguageTextProducer.java#L12

You can have discrepancies between displayable text and the audible sounds

**Comment by Eddy-Hoevenaers** [comment]
Removed the voiceMap, added the spoken files to the resource bundles
