### ISSUE TITLE
Code maturity: properly implement a builder (or don't use it)

### ISSUE THREAD

**Issue by kvandermast** [pwc-technology-be/eu-captcha#37]
There's quite some "wrongs" in the builder:

- Captcha.Builder should build a `Captcha` object, now it just encapsulates the builder in the object and returns the values from the builder; The values of the Captcha object should be set from the Builder during construction time, making it immutable;
- There is no reference required to the builder in Captcha, you should assign the values from the builder to the instance during creation (deep copy where required)
- There is no validation of the state of the object before being built: the `build()` method should validate before building, throwing IAE's when there is a missing value in your builder
- Methods of the builder are not uniform, either be verbose (addNoise, addRenderer, ....) or using more fluent styles (noise, renderer, ...)
- Maybe implement a static Captcha.newBuilder() which returns a new builder instances.
- Properly implementing your builder would not require it to be serializable.

https://github.com/pwc-technology-be/eu-captcha/blob/a9afdc95b4483782034d7dc4c9b39efbbc9e8bf0/src/main/java/com/sii/eucaptcha/captcha/Captcha.java#L31

**Comment by Eddy-Hoevenaers** [comment]
I improved the builder, the object constructor takes the builder properties and making this immutable
