### ISSUE TITLE
Performance: reuse SecureRandom instances

### ISSUE THREAD

**Issue by kvandermast** [pwc-technology-be/eu-captcha#38]
SecureRandom instances can be costly as it needs to be reseeded with every creation, reuse a single instance throughout the code.

https://github.com/pwc-technology-be/eu-captcha/blob/a9afdc95b4483782034d7dc4c9b39efbbc9e8bf0/src/main/java/com/sii/eucaptcha/captcha/text/textRender/impl/CaptchaTextRender.java#L26

**Comment by Eddy-Hoevenaers** [comment]
Implemented SecureRandom claas and reused this value throughout the code
