### ISSUE TITLE
Code maturity: proof of mis-use builder pattern

### ISSUE THREAD

**Issue by kvandermast** [pwc-technology-be/eu-captcha#39]
- why is "bg" excluded from noise? 
- it shows that there is no good understanding of how you should use a builder pattern

https://github.com/pwc-technology-be/eu-captcha/blob/a9afdc95b4483782034d7dc4c9b39efbbc9e8bf0/src/main/java/com/sii/eucaptcha/service/CaptchaService.java#L132-L141

**Comment by Eddy-Hoevenaers** [comment]
Removed the if structure and improved the builders
