### ISSUE TITLE
Abandonware?

### ISSUE THREAD

**Issue by tttp** [pwc-technology-be/eu-captcha#42]
Hi,

What's the status of this software? is this used somewhere, do you have some benchmark or manual?

And is there any plan to maintain it or is this just a "share as it is"?

In any case, thanks for publishing it here ;)

**Comment by YvesMeersmans** [comment]
Hi Xavier,

Thank you for your interest.

The software, as v1.0 was developed in 2020 as an action under the European Commission's ISA² framework. Further work is being undertaken as we speak. By the end of the year, you can expect WCAG level AA compliance, updates to the code depending on user feedback as well as a cloud-operated managed service (for European Commission services). 

An API implementation manual is available in the base files.
