### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by YvesMeersmans** [pwc-technology-be/eu-captcha#51]
Certain requests fail to be accepted

**Comment by Eddy-Hoevenaers** [comment]
I adapted the implementation to the level that is provided in the official Spring documentation: https://docs.spring.io/spring-framework/docs/5.3.4/reference/html/web.html#mvc-cors-global

**Comment by Eddy-Hoevenaers** [comment]
After our call the CORS issue is solved, Stan mailed also a confirmation after deploying the latest war file
