### ISSUE TITLE
CAPTCHA image: characters outside of image

### ISSUE THREAD

**Issue by YvesMeersmans** [pwc-technology-be/eu-captcha#52]
Sometimes the characters appear outside of the CAPTCHA image

**Comment by Eddy-Hoevenaers** [comment]
Fixed in the latest pull request

**Comment by YvesMeersmans** [comment]
@Eddy-Hoevenaers Please, please fix this in a way that the characters are detected and are **for sure** not outside of the image. Only after ten tries I already encounter an image with the biggest part of a character being outside of the frame... 
![image](https://user-images.githubusercontent.com/34094951/110096191-f6ddca80-7d9d-11eb-8fed-ed1ea758a425.png)

**Comment by YvesMeersmans** [comment]
Another example... 
![image](https://user-images.githubusercontent.com/34094951/110096327-183eb680-7d9e-11eb-97ef-7caede86d56c.png)

**Comment by Eddy-Hoevenaers** [comment]
Are you sure this is the latest war file that is deployed?

**Comment by YvesMeersmans** [comment]
@Eddy-Hoevenaers It should be, yes, since this was in a pull request from earlier. Stan is again redeploying with your latest pull request of this morning.

**Comment by Eddy-Hoevenaers** [comment]
I deployed it on our server at SII and i don't have it there. I send a mail for a short call to show it to you

**Comment by Eddy-Hoevenaers** [comment]
I moved the text a little more to the left side of the image
