### ISSUE TITLE
CAPTCHA image: characters not clearly readable

### ISSUE THREAD

**Issue by YvesMeersmans** [pwc-technology-be/eu-captcha#53]
Most CAPTCHA images are not solvable due to 

1. **unclear capitalization** ;
2. **distancing between characters**

**Comment by YvesMeersmans** [comment]
Relevant feedback from stakeholders:

- I am not sure to see the difference between 0 and o or O characters
- The letters which are same in Capital and small form are problematic to understand ( e.g. S & s , v & V , C & c , O & o) 
- Sometimes in captcha 2 letters are written without a gap and in captcha image it is not understood , if they are 2 separate letters or a shadow of a single letter or something else ( e.g. “ID” in captcha I and D are written together without gap , so it is difficult to understand they are 2 different letters or a shadow of letter D)

**Comment by YvesMeersmans** [comment]
I suggest to include one font for the capital letters (ideally a Serif/typewriter font so that you see the big letters easily), and another font (Sans-serif/smooth) for small letters.

**Comment by Eddy-Hoevenaers** [comment]
Added different Fonts for capital and small characters, the pull request only hold this change

**Comment by YvesMeersmans** [comment]
It has improved, yes. As mentioned before, we need to still include a tooltip for users to make them aware that Serif characters are capital and Sans-Serif characters are non-capital.
