### ISSUE TITLE
Re-architecture and Integrate it with eUI framework

### ISSUE THREAD

**Issue by jsatec-pm** [pwc-technology-be/EU-CAPTCHA#64]
Hi,

Thanks for the initiative, could you, By order of priority:

1) "rearchitecture" the software to make a version compatible with
- a. Angular (front end)
- b.Rest API (back end)
- c. Provide examples working with those technologies

2) Integrate it in eUI: https://eui.ecdevops.eu/

Kind regards,

**Comment by YvesMeersmans** [comment]
Hello. Angular front end and Rest API back end are now foreseen. The integration with eUI is to be foreseen in future major version(s).
