### ISSUE TITLE
Version available on line to test

### ISSUE THREAD

**Issue by jsatec-pm** [pwc-technology-be/EU-CAPTCHA#65]
Hi,

Would it be possible that you make available a version online in a test environment so that we can test and see how the captcha looks like.
This will allow to already see if we are interested in it.
And if yes, this will help us to provide you feedbacks already, just based on usability and accessibility testing.
This is allowing our testers to validate it without the need to build and deploy it on our servers.
Thank you,
Kind regards,

**Comment by Eddy-Hoevenaers** [comment]
I think this issue can be closed as there is a follow up issue, GitHub issue 78
