### ISSUE TITLE
Audio CAPTCHA improvements

### ISSUE THREAD

**Issue by YvesMeersmans** [pwc-technology-be/eu-captcha#70]
Two elements of feedback:

- There should be an interruption of minimum number of seconds between each letter / figure being spoken. This way increases the understanding of the audio CAPTCHA.
- The background noise should be very slightly toned down

**Comment by Eddy-Hoevenaers** [comment]
In the latest pull request there is an interruption between the spoken characters and the noise volume is decreased.
