### ISSUE TITLE
Rotation/what's up CAPTCHA not always correctly validated

### ISSUE THREAD

**Issue by YvesMeersmans** [pwc-technology-be/eu-captcha#89]
The new Rotation/what's up CAPTCHA is not always being correctly validated. I drag the slides to put the image in the right direction, but when validating, it shows that it is not correct. This happens most often with Messi and the sad dog. 
![download (messi)](https://user-images.githubusercontent.com/34094951/116226942-de61af00-a753-11eb-9efd-c74e17af471c.png)
![download (sad dog)](https://user-images.githubusercontent.com/34094951/116226947-df92dc00-a753-11eb-8f48-d82bc10bc119.png)

**Comment by Eddy-Hoevenaers** [comment]
These images where validated correctly but the images are confusing, for example the image with Messi is correct when his head is on top and then the lights aren't straight. For the dog goes the same, also confusing.

**Comment by YvesMeersmans** [comment]
Hi @Eddy-Hoevenaers Thanks for looking into this. What do you suggest? Shall we remove these two images and will you replace them with two improved images?

**Comment by Eddy-Hoevenaers** [comment]
I will check for 2 other images

**Comment by Eddy-Hoevenaers** [comment]
As said, 2 new images are added and the ones that where confusing are removed
