### ISSUE TITLE
Small issue/suggestion: Images should be in lower resolution

### ISSUE THREAD

**Issue by YvesMeersmans** [pwc-technology-be/eu-captcha#90]
The images currently included in the base files for the what's up CAPTCHA are too high res. They take up space and require more processing power/loading time. 

Please reduce the resolution. 

Even better, include in the code something that automatically reduces the resolution of the images to a fixed resolution. That way, anyone can link their image database and the images would be reduced in resolution automatically too.

**Comment by Eddy-Hoevenaers** [comment]
Image processing is an expensive operation in terms of resources, so picking the highest quality is not necessarily the best option when we don't really need it.

Let's see the performance of all of the approaches. We took one 1920×1920 px image, and scaled it to 200×200 px. The resulting observed times are as follows:

java.awt.Graphics2D – 34ms
Image.getScaledInstance() – 235ms
Imgscalr – 143ms
Thumbnailator –  547ms
Marvin – 361ms
Also, while defining the target image width and height, we should pay attention to the image aspect ratio. This way image will preserve its original proportions and will not be stretched.

**Comment by Eddy-Hoevenaers** [comment]
In my previous comment i added the processing time for different scaling operations, in our code at the moment we use java.awt.Graphics2D which seems to be the cheapest processing. 
So i propose to change nothing in the code that processes the image, on the other hand i saw that our example images are not all small. For example the 'Messi' image is 1,6 MB and one of the houses is 3,0MB, maybe we can change these images for smaller ones.

Yves, what do you think?

**Comment by Eddy-Hoevenaers** [comment]
Changed the largest images, the largest image is now 550kb
