### ISSUE TITLE
Buttons for rotating left and right do not work when rotation angle is negative

### ISSUE THREAD

**Issue by YvesMeersmans** [pwc-technology-be/EU-CAPTCHA#91]
After rotating the image in the what's up CAPTCHA first with the slider, so that the rotation angle is negative, the buttons for turning left and right do not work anymore. 
The buttons only work when the rotation angle is positive.

**Comment by Eddy-Hoevenaers** [comment]
Like we discussed in our meeting, it is the goal to use one of the 2 options (slider or buttons) to solve the captcha

**Comment by YvesMeersmans** [comment]
@Eddy-Hoevenaers I am surprised there is no way to fix this easily. Why can't you make the value that is being checked/changed by the buttons and the slider identical? 

If there is no fix, we then need to :

- very clearly explain in the documentation that it is not possible
- And make only one option visible by default in the default user interface. I suggest to include a toggle switch in the user interface so testers can choose themselves what to use. Please implement this (or a fix)

**Comment by Eddy-Hoevenaers** [comment]
Added toggle to backend files and clientfiles

**Comment by YvesMeersmans** [comment]
Thanks @Eddy-Hoevenaers . Did you also add the explanation/reason for the toggle to the documentation?
https://github.com/pwc-technology-be/eu-captcha/blob/master/EU%20CAPTCHA%20API%20implementation%20manual_v1.0.docx
